jobs:
  include:
    - stage: test
      dist: trusty
      sudo: required
      language: ruby
      cache:
        - bundler
      rvm: 2.4.4
      env:
        - RISKIFIED_SHOP_DOMAIN=www.recharge.com
        - RISKIFIED_DEFAULT_REFERRER=www.cg.nl
      script:
        - bundle exec rspec